name: build-and-test

on:
  pull_request:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 5.0.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Init for CI
        run: ./script/ci-init

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install Git dependencies
        run: ./script/install-git-deps

      - name: Install dependencies
        run: opam pin . --with-doc --with-test --yes

      - name: Build and test
        run: ./script/ci
